/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\Seger\Desktop\city-of-stories\city-of-stories\public\model\winterfest-area.glb 
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { POI } from '../components/POI/POI'
import { POI_DATA } from '../data/poiData'

export function Model(props) {
  const { onPOIClick, isTourMode, onModelLoaded } = props
  const hasLoadedRef = useRef(false)
  const { nodes, materials } = useGLTF('/model/winterfest-area.glb')
  
  useEffect(() => {
    if (nodes && materials && !hasLoadedRef.current) {
      hasLoadedRef.current = true
      
      setTimeout(() => {
        if (onModelLoaded) {
          onModelLoaded()
        }
      }, 600)
    }
  }, [nodes, materials, onModelLoaded])
  
  const handlePOIClick = (position, label, text, poiId) => {
    if (onPOIClick) {
      onPOIClick(position, label, text, poiId)
    }
  }
  
  return (
    <group {...props} dispose={null}>
      {!isTourMode && POI_DATA.map((poi) => (
        <POI 
          key={poi.id}
          position={poi.position} 
          label={poi.label} 
          text={poi.text} 
          onClick={() => handlePOIClick(poi.position, poi.label, poi.text, poi.id)} 
        />
      ))}
      <group position={[0, -0.061, 0]} scale={[1.577, 0.798, 1.577]}>
        <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials.metal} />
      </group>
      <mesh geometry={nodes.tree.geometry} material={materials.bush} position={[-22.268, 8.211, -17.025]} rotation={[0, 0.294, 0]} scale={[1.935, 1.368, 1.935]} />
      <mesh geometry={nodes.tree001.geometry} material={materials.bush} position={[-7.249, 3.402, 16.172]} rotation={[0, 0.294, 0]} scale={[0.764, 0.54, 0.764]} />
      <mesh geometry={nodes.tree002.geometry} material={materials.bush} position={[-21.975, 3.402, 16.172]} rotation={[0, 0.294, 0]} scale={[0.764, 0.54, 0.764]} />
      <mesh geometry={nodes.tree003.geometry} material={materials.bush} position={[28.29, 3.348, 18.517]} rotation={[0, 0.294, 0]} scale={[0.764, 0.54, 0.764]} />
      <mesh geometry={nodes.tree004.geometry} material={materials.bush} position={[35.15, 3.348, 11.055]} rotation={[0, 0.294, 0]} scale={[0.764, 0.54, 0.764]} />
      <mesh geometry={nodes.tree005.geometry} material={materials.bush} position={[32.64, 3.345, -26.576]} rotation={[0, 0.294, 0]} scale={[0.764, 0.54, 0.764]} />
      <mesh geometry={nodes.tree006.geometry} material={materials.bush} position={[24.178, 3.345, -32.687]} rotation={[0, 0.294, 0]} scale={[0.764, 0.54, 0.764]} />
      <mesh geometry={nodes.tree007.geometry} material={materials.bush} position={[-24.649, 3.219, -30.782]} rotation={[0, 0.294, 0]} scale={[0.745, 0.527, 0.745]} />
      <mesh geometry={nodes.tree008.geometry} material={materials.bush} position={[-34.22, 3.219, -22.966]} rotation={[0, 0.294, 0]} scale={[0.745, 0.527, 0.745]} />
      <mesh geometry={nodes['tree-part'].geometry} material={materials.bush} position={[26.258, 0, -6.965]} scale={1.682} />
      <mesh geometry={nodes['tree-part002'].geometry} material={materials.bush} position={[26.258, 0, 3.758]} scale={1.682} />
      <mesh geometry={nodes['tree-part003'].geometry} material={materials.bush} position={[30.032, 0, 13.552]} rotation={[0, 0.837, 0]} scale={1.682} />
      <mesh geometry={nodes['tree-part004'].geometry} material={materials.bush} position={[27.064, -0.223, -27.788]} rotation={[0, -0.663, 0]} scale={1.682} />
      <mesh geometry={nodes['tree-part005'].geometry} material={materials.bush} position={[26.258, 0, -18.987]} scale={1.682} />
      <mesh geometry={nodes['tree-part007'].geometry} material={materials.bush} position={[-27.304, 0, -12.059]} scale={1.682} />
      <mesh geometry={nodes['tree-part008'].geometry} material={materials.bush} position={[-27.304, 0, 4.437]} scale={1.682} />
      <mesh geometry={nodes['tree-part010'].geometry} material={materials.bush} position={[-16.023, 0, 9.428]} rotation={[0, 1.512, 0]} scale={1.682} />
      <mesh geometry={nodes['tree-part011'].geometry} material={materials.bush} position={[-27.304, 0, 14.37]} scale={1.682} />
      <mesh geometry={nodes['tree-part012'].geometry} material={materials.bush} position={[20.167, 0, 9.428]} rotation={[0, 1.512, 0]} scale={1.682} />
      <mesh geometry={nodes['tree-part013'].geometry} material={materials.bush} position={[20.167, 0, -25.168]} rotation={[0, 1.512, 0]} scale={1.682} />
      <mesh geometry={nodes['tree-part015'].geometry} material={materials.bush} position={[7.64, 0, -25.168]} rotation={[0, 1.512, 0]} scale={1.682} />
      <mesh geometry={nodes['tree-part019'].geometry} material={materials.bush} position={[-17.111, 0, -25.168]} rotation={[0, 1.512, 0]} scale={1.682} />
      <mesh geometry={nodes['tree-part020'].geometry} material={materials.bush} position={[-29.414, 0.015, -26.978]} rotation={[0, 0.657, 0]} scale={1.682} />
      <mesh geometry={nodes['tree-part022'].geometry} material={materials.bush} position={[7.64, 0, 9.222]} rotation={[0, 1.512, 0]} scale={1.682} />
      <mesh geometry={nodes['tree-part024'].geometry} material={materials.bush} position={[-7.294, 0, 9.222]} rotation={[0, 1.512, 0]} scale={1.682} />
      <mesh geometry={nodes['tree-part001'].geometry} material={materials.bush} position={[-6.168, 0, -25.168]} rotation={[0, 1.512, 0]} scale={1.682} />
      <mesh geometry={nodes['tree-part006'].geometry} material={materials.bush} position={[-26.999, 0, 26.409]} scale={1.682} />
    </group>
  )
}

useGLTF.preload('/model/winterfest-area.glb')
